package com.trungndz.classroombook.entities;
// Generated 14-Dec-2018 15:20:34 by Hibernate Tools 4.3.5.Final

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Position generated by hbm2java
 */
@Entity
@Table(name = "position", schema = "public")
public class Position implements java.io.Serializable {

	private int idposition;
	private String position;
	private List<Employee> employees;

	public Position() {
	}

	public Position(int idposition) {
		this.idposition = idposition;
	}

	public Position(int idposition, String position, List<Employee> employees) {
		this.idposition = idposition;
		this.position = position;
		this.employees = employees;
	}

	@Id

	@Column(name = "idposition", unique = true, nullable = false)
	public int getIdposition() {
		return this.idposition;
	}

	public void setIdposition(int idposition) {
		this.idposition = idposition;
	}

	@Column(name = "position", length = 50)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "position")
	@JsonBackReference
	public List<Employee> getEmployees() {
		return employees;
	}

	public void setEmployees(List<Employee> employees) {
		this.employees = employees;
	}


}
