package com.trungndz.classroombook.entities;
// Generated 14-Dec-2018 15:20:34 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Roomsession generated by hbm2java
 */
@Entity
@Table(name = "roomsession", schema = "public")
public class Roomsession implements java.io.Serializable {

	private RoomsessionId id;
	private Employee creator;
	private Employee subscriber;
	private Employee approver;
	private Room room;
	private Shiftsession shiftsession;

	public Roomsession() {
	}

	public Roomsession(RoomsessionId id, Employee creator, Room room, Shiftsession shiftsession) {
		this.id = id;
		this.creator = creator;
		this.room = room;
		this.shiftsession = shiftsession;
	}

	public Roomsession(RoomsessionId id, Employee creator, Employee subscriber,
			Employee approver, Room room, Shiftsession shiftsession) {
		this.id = id;
		this.creator = creator;
		this.subscriber = subscriber;
		this.approver = approver;
		this.room = room;
		this.shiftsession = shiftsession;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idroom", column = @Column(name = "idroom", nullable = false)),
			@AttributeOverride(name = "idsession", column = @Column(name = "idsession", nullable = false)),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false, length = 13)) })
	public RoomsessionId getId() {
		return this.id;
	}

	public void setId(RoomsessionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonBackReference
	@JoinColumn(name = "creator", nullable = false)
	public Employee getcreator() {
		return this.creator;
	}

	public void setcreator(Employee creator) {
		this.creator = creator;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonBackReference
	@JoinColumn(name = "subscriber")
	public Employee getsubscriber() {
		return this.subscriber;
	}

	public void setsubscriber(Employee subscriber) {
		this.subscriber = subscriber;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonBackReference
	@JoinColumn(name = "approver")
	public Employee getapprover() {
		return this.approver;
	}

	public void setapprover(Employee approver) {
		this.approver = approver;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonBackReference
	@JoinColumn(name = "idroom", nullable = false, insertable = false, updatable = false)
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JsonBackReference
	@JoinColumn(name = "idsession", nullable = false, insertable = false, updatable = false)
	public Shiftsession getShiftsession() {
		return this.shiftsession;
	}

	public void setShiftsession(Shiftsession shiftsession) {
		this.shiftsession = shiftsession;
	}

}
