package com.trungndz.classroombook.entities;
// Generated 14-Dec-2018 15:20:34 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Shiftsession generated by hbm2java
 */
@Entity
@Table(name = "shiftsession", schema = "public")
public class Shiftsession implements java.io.Serializable {

	private int idsession;
	private Set<Roomsession> roomsessions = new HashSet<Roomsession>(0);

	public Shiftsession() {
	}

	public Shiftsession(int idsession) {
		this.idsession = idsession;
	}

	public Shiftsession(int idsession, Set<Roomsession> roomsessions) {
		this.idsession = idsession;
		this.roomsessions = roomsessions;
	}

	@Id

	@Column(name = "idsession", unique = true, nullable = false)
	public int getIdsession() {
		return this.idsession;
	}

	public void setIdsession(int idsession) {
		this.idsession = idsession;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shiftsession")
	@JsonBackReference
	public Set<Roomsession> getRoomsessions() {
		return this.roomsessions;
	}

	public void setRoomsessions(Set<Roomsession> roomsessions) {
		this.roomsessions = roomsessions;
	}

}
