package com.trungndz.classroombook.entities;
// Generated 12-Dec-2018 00:21:12 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Position generated by hbm2java
 */
@Entity
@Table(name = "position", schema = "public")
public class Position implements java.io.Serializable {

	private int idposition;
	private String position;

	public Position() {
	}

	public Position(int idposition) {
		this.idposition = idposition;
	}

	public Position(int idposition, String position) {
		this.idposition = idposition;
		this.position = position;
	}

	@Id

	@Column(name = "idposition", unique = true, nullable = false)
	public int getIdposition() {
		return this.idposition;
	}

	public void setIdposition(int idposition) {
		this.idposition = idposition;
	}

	@Column(name = "position", length = 50)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

}
