package com.trungndz.classroombook.entities;
// Generated 12-Dec-2018 00:21:12 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name = "room", schema = "public")
public class Room implements java.io.Serializable {

	private int idroom;
	private String roomname;
	private Integer seatamount;

	public Room() {
	}

	public Room(int idroom) {
		this.idroom = idroom;
	}

	public Room(int idroom, String roomname, Integer seatamount) {
		this.idroom = idroom;
		this.roomname = roomname;
		this.seatamount = seatamount;
	}

	@Id

	@Column(name = "idroom", unique = true, nullable = false)
	public int getIdroom() {
		return this.idroom;
	}

	public void setIdroom(int idroom) {
		this.idroom = idroom;
	}

	@Column(name = "roomname", length = 50)
	public String getRoomname() {
		return this.roomname;
	}

	public void setRoomname(String roomname) {
		this.roomname = roomname;
	}

	@Column(name = "seatamount")
	public Integer getSeatamount() {
		return this.seatamount;
	}

	public void setSeatamount(Integer seatamount) {
		this.seatamount = seatamount;
	}

}
