package com.trungndz.classroombook.entities;
// Generated 12-Dec-2018 00:21:12 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Shiftsession generated by hbm2java
 */
@Entity
@Table(name = "shiftsession", schema = "public")
public class Shiftsession implements java.io.Serializable {

	private int idsession;

	public Shiftsession() {
	}

	public Shiftsession(int idsession) {
		this.idsession = idsession;
	}

	@Id

	@Column(name = "idsession", unique = true, nullable = false)
	public int getIdsession() {
		return this.idsession;
	}

	public void setIdsession(int idsession) {
		this.idsession = idsession;
	}

}
